# Generated by Django 5.1.6 on 2025-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('blogTitle', models.CharField(max_length=300)),
                ('blogDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
