# Generated by Django 5.1.6 on 2025-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='bid',
            field=models.CharField(default=1234567893, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
