# Generated by Django 5.1.6 on 2025-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_bid_blogs_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/blog_photos/'),
        ),
    ]
